// @generated by protoc-gen-es v1.2.0
// @generated from file provider/v1/idnow.proto (package provider.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Any, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message provider.v1.IDnowSuccessPayload
 */
export const IDnowSuccessPayload = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowSuccessPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowSuccessPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowSuccessPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowSuccessPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowSuccessPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowSuccessPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Identificationprocess
 */
export const IDnowSuccessPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Customdata
 */
export const IDnowSuccessPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowSuccessPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Contactdata
 */
export const IDnowSuccessPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "message", T: Any },
    { no: 2, name: "email", kind: "message", T: Any },
  ],
  {localName: "IDnowSuccessPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Birthday
 */
export const IDnowSuccessPayload_Birthday = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Birthday",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Birthday"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Firstname
 */
export const IDnowSuccessPayload_Firstname = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Firstname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Firstname"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Address
 */
export const IDnowSuccessPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Address",
  [],
  {localName: "IDnowSuccessPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Birthplace
 */
export const IDnowSuccessPayload_Birthplace = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Birthplace",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Birthplace"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Nationality
 */
export const IDnowSuccessPayload_Nationality = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Nationality",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Nationality"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Gender
 */
export const IDnowSuccessPayload_Gender = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Gender",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Gender"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Identlanguage
 */
export const IDnowSuccessPayload_Identlanguage = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Identlanguage",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Identlanguage"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Birthname
 */
export const IDnowSuccessPayload_Birthname = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Birthname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Birthname"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Lastname
 */
export const IDnowSuccessPayload_Lastname = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Lastname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Lastname"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Userdata
 */
export const IDnowSuccessPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Userdata",
  () => [
    { no: 1, name: "birthday", kind: "message", T: IDnowSuccessPayload_Birthday },
    { no: 2, name: "firstname", kind: "message", T: IDnowSuccessPayload_Firstname },
    { no: 3, name: "address", kind: "message", T: IDnowSuccessPayload_Address },
    { no: 4, name: "birthplace", kind: "message", T: IDnowSuccessPayload_Birthplace },
    { no: 5, name: "nationality", kind: "message", T: IDnowSuccessPayload_Nationality },
    { no: 6, name: "gender", kind: "message", T: IDnowSuccessPayload_Gender },
    { no: 7, name: "identlanguage", kind: "message", T: IDnowSuccessPayload_Identlanguage },
    { no: 8, name: "birthname", kind: "message", T: IDnowSuccessPayload_Birthname },
    { no: 9, name: "lastname", kind: "message", T: IDnowSuccessPayload_Lastname },
  ],
  {localName: "IDnowSuccessPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Country
 */
export const IDnowSuccessPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Number
 */
export const IDnowSuccessPayload_Number = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Number",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Number"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Issuedby
 */
export const IDnowSuccessPayload_Issuedby = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Issuedby",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Issuedby"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Dateissued
 */
export const IDnowSuccessPayload_Dateissued = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Dateissued",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Dateissued"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Type
 */
export const IDnowSuccessPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Validuntil
 */
export const IDnowSuccessPayload_Validuntil = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Validuntil",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Validuntil"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Identificationdocument
 */
export const IDnowSuccessPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowSuccessPayload_Country },
    { no: 2, name: "number", kind: "message", T: IDnowSuccessPayload_Number },
    { no: 3, name: "issuedby", kind: "message", T: IDnowSuccessPayload_Issuedby },
    { no: 4, name: "dateissued", kind: "message", T: IDnowSuccessPayload_Dateissued },
    { no: 5, name: "type", kind: "message", T: IDnowSuccessPayload_Type },
    { no: 6, name: "validuntil", kind: "message", T: IDnowSuccessPayload_Validuntil },
    { no: 7, name: "driverlicenses", kind: "message", T: Any, repeated: true },
  ],
  {localName: "IDnowSuccessPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowSuccessPayload.Attachments
 */
export const IDnowSuccessPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowSuccessPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "idfrontside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessPayload_Attachments"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload
 */
export const IDnowReviewPendingPayload = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowReviewPendingPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowReviewPendingPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowReviewPendingPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowReviewPendingPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowReviewPendingPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowReviewPendingPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Identificationprocess
 */
export const IDnowReviewPendingPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Customdata
 */
export const IDnowReviewPendingPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowReviewPendingPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Contactdata
 */
export const IDnowReviewPendingPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Birthday
 */
export const IDnowReviewPendingPayload_Birthday = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Birthday",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Birthday"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Firstname
 */
export const IDnowReviewPendingPayload_Firstname = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Firstname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Firstname"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Zipcode
 */
export const IDnowReviewPendingPayload_Zipcode = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Zipcode",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Zipcode"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Country
 */
export const IDnowReviewPendingPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.City
 */
export const IDnowReviewPendingPayload_City = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.City",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_City"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Street
 */
export const IDnowReviewPendingPayload_Street = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Street",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Street"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Streetnumber
 */
export const IDnowReviewPendingPayload_Streetnumber = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Streetnumber",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Streetnumber"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Address
 */
export const IDnowReviewPendingPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Address",
  () => [
    { no: 1, name: "zipcode", kind: "message", T: IDnowReviewPendingPayload_Zipcode },
    { no: 2, name: "country", kind: "message", T: IDnowReviewPendingPayload_Country },
    { no: 3, name: "city", kind: "message", T: IDnowReviewPendingPayload_City },
    { no: 4, name: "street", kind: "message", T: IDnowReviewPendingPayload_Street },
    { no: 5, name: "streetnumber", kind: "message", T: IDnowReviewPendingPayload_Streetnumber },
  ],
  {localName: "IDnowReviewPendingPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Birthplace
 */
export const IDnowReviewPendingPayload_Birthplace = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Birthplace",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Birthplace"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Nationality
 */
export const IDnowReviewPendingPayload_Nationality = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Nationality",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Nationality"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Gender
 */
export const IDnowReviewPendingPayload_Gender = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Gender",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Gender"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Identlanguage
 */
export const IDnowReviewPendingPayload_Identlanguage = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Identlanguage",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Identlanguage"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Lastname
 */
export const IDnowReviewPendingPayload_Lastname = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Lastname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Lastname"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Userdata
 */
export const IDnowReviewPendingPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Userdata",
  () => [
    { no: 1, name: "birthday", kind: "message", T: IDnowReviewPendingPayload_Birthday },
    { no: 2, name: "firstname", kind: "message", T: IDnowReviewPendingPayload_Firstname },
    { no: 3, name: "address", kind: "message", T: IDnowReviewPendingPayload_Address },
    { no: 4, name: "birthplace", kind: "message", T: IDnowReviewPendingPayload_Birthplace },
    { no: 5, name: "nationality", kind: "message", T: IDnowReviewPendingPayload_Nationality },
    { no: 6, name: "gender", kind: "message", T: IDnowReviewPendingPayload_Gender },
    { no: 7, name: "identlanguage", kind: "message", T: IDnowReviewPendingPayload_Identlanguage },
    { no: 8, name: "lastname", kind: "message", T: IDnowReviewPendingPayload_Lastname },
  ],
  {localName: "IDnowReviewPendingPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Country1
 */
export const IDnowReviewPendingPayload_Country1 = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Country1",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Country1"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Number
 */
export const IDnowReviewPendingPayload_Number = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Number",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Number"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Type
 */
export const IDnowReviewPendingPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Validuntil
 */
export const IDnowReviewPendingPayload_Validuntil = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Validuntil",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Validuntil"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Identificationdocument
 */
export const IDnowReviewPendingPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowReviewPendingPayload_Country1 },
    { no: 2, name: "number", kind: "message", T: IDnowReviewPendingPayload_Number },
    { no: 3, name: "type", kind: "message", T: IDnowReviewPendingPayload_Type },
    { no: 4, name: "validuntil", kind: "message", T: IDnowReviewPendingPayload_Validuntil },
    { no: 5, name: "driverlicenses", kind: "message", T: Any, repeated: true },
  ],
  {localName: "IDnowReviewPendingPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowReviewPendingPayload.Attachments
 */
export const IDnowReviewPendingPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowReviewPendingPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "idbackside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "idfrontside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowReviewPendingPayload_Attachments"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload
 */
export const IDnowFraudSuspicionPendingPayload = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowFraudSuspicionPendingPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowFraudSuspicionPendingPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowFraudSuspicionPendingPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowFraudSuspicionPendingPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowFraudSuspicionPendingPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowFraudSuspicionPendingPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Identificationprocess
 */
export const IDnowFraudSuspicionPendingPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Customdata
 */
export const IDnowFraudSuspicionPendingPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Contactdata
 */
export const IDnowFraudSuspicionPendingPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "message", T: Any },
    { no: 2, name: "email", kind: "message", T: Any },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Address
 */
export const IDnowFraudSuspicionPendingPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Address",
  [],
  {localName: "IDnowFraudSuspicionPendingPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Userdata
 */
export const IDnowFraudSuspicionPendingPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Userdata",
  () => [
    { no: 1, name: "address", kind: "message", T: IDnowFraudSuspicionPendingPayload_Address },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Country
 */
export const IDnowFraudSuspicionPendingPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Type
 */
export const IDnowFraudSuspicionPendingPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Identificationdocument
 */
export const IDnowFraudSuspicionPendingPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowFraudSuspicionPendingPayload_Country },
    { no: 2, name: "type", kind: "message", T: IDnowFraudSuspicionPendingPayload_Type },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionPendingPayload.Attachments
 */
export const IDnowFraudSuspicionPendingPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionPendingPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "idbackside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "idfrontside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "userface", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "livenessleft", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "livenessright", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionPendingPayload_Attachments"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload
 */
export const IDnowSuccessDataChangedPayload = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowSuccessDataChangedPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowSuccessDataChangedPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowSuccessDataChangedPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowSuccessDataChangedPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowSuccessDataChangedPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowSuccessDataChangedPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Identificationprocess
 */
export const IDnowSuccessDataChangedPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Customdata
 */
export const IDnowSuccessDataChangedPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Contactdata
 */
export const IDnowSuccessDataChangedPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Birthday
 */
export const IDnowSuccessDataChangedPayload_Birthday = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Birthday",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Birthday"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Firstname
 */
export const IDnowSuccessDataChangedPayload_Firstname = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Firstname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Firstname"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Zipcode
 */
export const IDnowSuccessDataChangedPayload_Zipcode = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Zipcode",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Zipcode"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Country
 */
export const IDnowSuccessDataChangedPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.City
 */
export const IDnowSuccessDataChangedPayload_City = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.City",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_City"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Street
 */
export const IDnowSuccessDataChangedPayload_Street = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Street",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Street"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Streetnumber
 */
export const IDnowSuccessDataChangedPayload_Streetnumber = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Streetnumber",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Streetnumber"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Address
 */
export const IDnowSuccessDataChangedPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Address",
  () => [
    { no: 1, name: "zipcode", kind: "message", T: IDnowSuccessDataChangedPayload_Zipcode },
    { no: 2, name: "country", kind: "message", T: IDnowSuccessDataChangedPayload_Country },
    { no: 3, name: "city", kind: "message", T: IDnowSuccessDataChangedPayload_City },
    { no: 4, name: "street", kind: "message", T: IDnowSuccessDataChangedPayload_Street },
    { no: 5, name: "streetnumber", kind: "message", T: IDnowSuccessDataChangedPayload_Streetnumber },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Birthplace
 */
export const IDnowSuccessDataChangedPayload_Birthplace = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Birthplace",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Birthplace"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Nationality
 */
export const IDnowSuccessDataChangedPayload_Nationality = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Nationality",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Nationality"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Gender
 */
export const IDnowSuccessDataChangedPayload_Gender = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Gender",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Gender"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Identlanguage
 */
export const IDnowSuccessDataChangedPayload_Identlanguage = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Identlanguage",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Identlanguage"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Lastname
 */
export const IDnowSuccessDataChangedPayload_Lastname = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Lastname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Lastname"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Userdata
 */
export const IDnowSuccessDataChangedPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Userdata",
  () => [
    { no: 1, name: "birthday", kind: "message", T: IDnowSuccessDataChangedPayload_Birthday },
    { no: 2, name: "firstname", kind: "message", T: IDnowSuccessDataChangedPayload_Firstname },
    { no: 3, name: "address", kind: "message", T: IDnowSuccessDataChangedPayload_Address },
    { no: 4, name: "birthplace", kind: "message", T: IDnowSuccessDataChangedPayload_Birthplace },
    { no: 5, name: "nationality", kind: "message", T: IDnowSuccessDataChangedPayload_Nationality },
    { no: 6, name: "gender", kind: "message", T: IDnowSuccessDataChangedPayload_Gender },
    { no: 7, name: "identlanguage", kind: "message", T: IDnowSuccessDataChangedPayload_Identlanguage },
    { no: 8, name: "lastname", kind: "message", T: IDnowSuccessDataChangedPayload_Lastname },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Country1
 */
export const IDnowSuccessDataChangedPayload_Country1 = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Country1",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Country1"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Number
 */
export const IDnowSuccessDataChangedPayload_Number = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Number",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Number"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Type
 */
export const IDnowSuccessDataChangedPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Validuntil
 */
export const IDnowSuccessDataChangedPayload_Validuntil = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Validuntil",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Validuntil"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Identificationdocument
 */
export const IDnowSuccessDataChangedPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowSuccessDataChangedPayload_Country1 },
    { no: 2, name: "number", kind: "message", T: IDnowSuccessDataChangedPayload_Number },
    { no: 3, name: "type", kind: "message", T: IDnowSuccessDataChangedPayload_Type },
    { no: 4, name: "validuntil", kind: "message", T: IDnowSuccessDataChangedPayload_Validuntil },
    { no: 5, name: "driverlicenses", kind: "message", T: Any, repeated: true },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowSuccessDataChangedPayload.Attachments
 */
export const IDnowSuccessDataChangedPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowSuccessDataChangedPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "idbackside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "idfrontside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowSuccessDataChangedPayload_Attachments"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload
 */
export const IDnowFraudSuspicionConfirmedPayload = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Identificationprocess
 */
export const IDnowFraudSuspicionConfirmedPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Customdata
 */
export const IDnowFraudSuspicionConfirmedPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Contactdata
 */
export const IDnowFraudSuspicionConfirmedPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Birthday
 */
export const IDnowFraudSuspicionConfirmedPayload_Birthday = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Birthday",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Birthday"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Firstname
 */
export const IDnowFraudSuspicionConfirmedPayload_Firstname = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Firstname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Firstname"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Zipcode
 */
export const IDnowFraudSuspicionConfirmedPayload_Zipcode = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Zipcode",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Zipcode"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Country
 */
export const IDnowFraudSuspicionConfirmedPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.City
 */
export const IDnowFraudSuspicionConfirmedPayload_City = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.City",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_City"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Street
 */
export const IDnowFraudSuspicionConfirmedPayload_Street = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Street",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Street"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Streetnumber
 */
export const IDnowFraudSuspicionConfirmedPayload_Streetnumber = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Streetnumber",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Streetnumber"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Address
 */
export const IDnowFraudSuspicionConfirmedPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Address",
  () => [
    { no: 1, name: "zipcode", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Zipcode },
    { no: 2, name: "country", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Country },
    { no: 3, name: "city", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_City },
    { no: 4, name: "street", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Street },
    { no: 5, name: "streetnumber", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Streetnumber },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Birthplace
 */
export const IDnowFraudSuspicionConfirmedPayload_Birthplace = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Birthplace",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Birthplace"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Nationality
 */
export const IDnowFraudSuspicionConfirmedPayload_Nationality = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Nationality",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Nationality"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Gender
 */
export const IDnowFraudSuspicionConfirmedPayload_Gender = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Gender",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Gender"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Identlanguage
 */
export const IDnowFraudSuspicionConfirmedPayload_Identlanguage = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Identlanguage",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Identlanguage"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Lastname
 */
export const IDnowFraudSuspicionConfirmedPayload_Lastname = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Lastname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Lastname"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Userdata
 */
export const IDnowFraudSuspicionConfirmedPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Userdata",
  () => [
    { no: 1, name: "birthday", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Birthday },
    { no: 2, name: "firstname", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Firstname },
    { no: 3, name: "address", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Address },
    { no: 4, name: "birthplace", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Birthplace },
    { no: 5, name: "nationality", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Nationality },
    { no: 6, name: "gender", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Gender },
    { no: 7, name: "identlanguage", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Identlanguage },
    { no: 8, name: "lastname", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Lastname },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Country1
 */
export const IDnowFraudSuspicionConfirmedPayload_Country1 = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Country1",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Country1"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Number
 */
export const IDnowFraudSuspicionConfirmedPayload_Number = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Number",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Number"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Type
 */
export const IDnowFraudSuspicionConfirmedPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Validuntil
 */
export const IDnowFraudSuspicionConfirmedPayload_Validuntil = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Validuntil",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Validuntil"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Identificationdocument
 */
export const IDnowFraudSuspicionConfirmedPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Country1 },
    { no: 2, name: "number", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Number },
    { no: 3, name: "type", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Type },
    { no: 4, name: "validuntil", kind: "message", T: IDnowFraudSuspicionConfirmedPayload_Validuntil },
    { no: 5, name: "driverlicenses", kind: "message", T: Any, repeated: true },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowFraudSuspicionConfirmedPayload.Attachments
 */
export const IDnowFraudSuspicionConfirmedPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowFraudSuspicionConfirmedPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "idbackside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "idfrontside", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowFraudSuspicionConfirmedPayload_Attachments"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload
 */
export const IDnowCanceledPayload = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowCanceledPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowCanceledPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowCanceledPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowCanceledPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowCanceledPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowCanceledPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Identificationprocess
 */
export const IDnowCanceledPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 6, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Customdata
 */
export const IDnowCanceledPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowCanceledPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Contactdata
 */
export const IDnowCanceledPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Birthday
 */
export const IDnowCanceledPayload_Birthday = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Birthday",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Birthday"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Firstname
 */
export const IDnowCanceledPayload_Firstname = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Firstname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Firstname"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Zipcode
 */
export const IDnowCanceledPayload_Zipcode = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Zipcode",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Zipcode"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Country
 */
export const IDnowCanceledPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.City
 */
export const IDnowCanceledPayload_City = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.City",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_City"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Street
 */
export const IDnowCanceledPayload_Street = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Street",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Street"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Streetnumber
 */
export const IDnowCanceledPayload_Streetnumber = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Streetnumber",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Streetnumber"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Address
 */
export const IDnowCanceledPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Address",
  () => [
    { no: 1, name: "zipcode", kind: "message", T: IDnowCanceledPayload_Zipcode },
    { no: 2, name: "country", kind: "message", T: IDnowCanceledPayload_Country },
    { no: 3, name: "city", kind: "message", T: IDnowCanceledPayload_City },
    { no: 4, name: "street", kind: "message", T: IDnowCanceledPayload_Street },
    { no: 5, name: "streetnumber", kind: "message", T: IDnowCanceledPayload_Streetnumber },
  ],
  {localName: "IDnowCanceledPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Birthplace
 */
export const IDnowCanceledPayload_Birthplace = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Birthplace",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "original", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Birthplace"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Nationality
 */
export const IDnowCanceledPayload_Nationality = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Nationality",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Nationality"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Gender
 */
export const IDnowCanceledPayload_Gender = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Gender",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Gender"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Identlanguage
 */
export const IDnowCanceledPayload_Identlanguage = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Identlanguage",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Identlanguage"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Lastname
 */
export const IDnowCanceledPayload_Lastname = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Lastname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Lastname"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Userdata
 */
export const IDnowCanceledPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Userdata",
  () => [
    { no: 1, name: "birthday", kind: "message", T: IDnowCanceledPayload_Birthday },
    { no: 2, name: "firstname", kind: "message", T: IDnowCanceledPayload_Firstname },
    { no: 3, name: "address", kind: "message", T: IDnowCanceledPayload_Address },
    { no: 4, name: "birthplace", kind: "message", T: IDnowCanceledPayload_Birthplace },
    { no: 5, name: "nationality", kind: "message", T: IDnowCanceledPayload_Nationality },
    { no: 6, name: "gender", kind: "message", T: IDnowCanceledPayload_Gender },
    { no: 7, name: "identlanguage", kind: "message", T: IDnowCanceledPayload_Identlanguage },
    { no: 8, name: "lastname", kind: "message", T: IDnowCanceledPayload_Lastname },
  ],
  {localName: "IDnowCanceledPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Country1
 */
export const IDnowCanceledPayload_Country1 = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Country1",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Country1"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Number
 */
export const IDnowCanceledPayload_Number = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Number",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Number"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Type
 */
export const IDnowCanceledPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Validuntil
 */
export const IDnowCanceledPayload_Validuntil = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Validuntil",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Validuntil"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Identificationdocument
 */
export const IDnowCanceledPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowCanceledPayload_Country1 },
    { no: 2, name: "number", kind: "message", T: IDnowCanceledPayload_Number },
    { no: 3, name: "type", kind: "message", T: IDnowCanceledPayload_Type },
    { no: 4, name: "validuntil", kind: "message", T: IDnowCanceledPayload_Validuntil },
    { no: 5, name: "driverlicenses", kind: "message", T: Any, repeated: true },
  ],
  {localName: "IDnowCanceledPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowCanceledPayload.Attachments
 */
export const IDnowCanceledPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowCanceledPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowCanceledPayload_Attachments"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload
 */
export const IDnowAbortedPayload = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload",
  () => [
    { no: 1, name: "identificationprocess", kind: "message", T: IDnowAbortedPayload_Identificationprocess },
    { no: 2, name: "customdata", kind: "message", T: IDnowAbortedPayload_Customdata },
    { no: 3, name: "contactdata", kind: "message", T: IDnowAbortedPayload_Contactdata },
    { no: 4, name: "userdata", kind: "message", T: IDnowAbortedPayload_Userdata },
    { no: 5, name: "identificationdocument", kind: "message", T: IDnowAbortedPayload_Identificationdocument },
    { no: 6, name: "attachments", kind: "message", T: IDnowAbortedPayload_Attachments },
  ],
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Identificationprocess
 */
export const IDnowAbortedPayload_Identificationprocess = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Identificationprocess",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "companyid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "identificationtime", kind: "message", T: Timestamp },
    { no: 6, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "href", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "transactionnumber", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Identificationprocess"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Customdata
 */
export const IDnowAbortedPayload_Customdata = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Customdata",
  () => [
    { no: 1, name: "custom3", kind: "message", T: Any },
    { no: 2, name: "custom4", kind: "message", T: Any },
    { no: 3, name: "custom1", kind: "message", T: Any },
    { no: 4, name: "custom2", kind: "message", T: Any },
    { no: 5, name: "custom5", kind: "message", T: Any },
  ],
  {localName: "IDnowAbortedPayload_Customdata"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Contactdata
 */
export const IDnowAbortedPayload_Contactdata = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Contactdata",
  () => [
    { no: 1, name: "mobilephone", kind: "message", T: Any },
    { no: 2, name: "email", kind: "message", T: Any },
  ],
  {localName: "IDnowAbortedPayload_Contactdata"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Firstname
 */
export const IDnowAbortedPayload_Firstname = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Firstname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Firstname"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Address
 */
export const IDnowAbortedPayload_Address = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Address",
  [],
  {localName: "IDnowAbortedPayload_Address"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Birthplace
 */
export const IDnowAbortedPayload_Birthplace = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Birthplace",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Birthplace"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Birthname
 */
export const IDnowAbortedPayload_Birthname = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Birthname",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Birthname"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Userdata
 */
export const IDnowAbortedPayload_Userdata = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Userdata",
  () => [
    { no: 1, name: "firstname", kind: "message", T: IDnowAbortedPayload_Firstname },
    { no: 2, name: "address", kind: "message", T: IDnowAbortedPayload_Address },
    { no: 3, name: "birthplace", kind: "message", T: IDnowAbortedPayload_Birthplace },
    { no: 4, name: "birthname", kind: "message", T: IDnowAbortedPayload_Birthname },
  ],
  {localName: "IDnowAbortedPayload_Userdata"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Country
 */
export const IDnowAbortedPayload_Country = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Country",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Country"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Issuedby
 */
export const IDnowAbortedPayload_Issuedby = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Issuedby",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Issuedby"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Type
 */
export const IDnowAbortedPayload_Type = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Type",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Type"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Identificationdocument
 */
export const IDnowAbortedPayload_Identificationdocument = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Identificationdocument",
  () => [
    { no: 1, name: "country", kind: "message", T: IDnowAbortedPayload_Country },
    { no: 2, name: "issuedby", kind: "message", T: IDnowAbortedPayload_Issuedby },
    { no: 3, name: "type", kind: "message", T: IDnowAbortedPayload_Type },
  ],
  {localName: "IDnowAbortedPayload_Identificationdocument"},
);

/**
 * @generated from message provider.v1.IDnowAbortedPayload.Attachments
 */
export const IDnowAbortedPayload_Attachments = proto3.makeMessageType(
  "provider.v1.IDnowAbortedPayload.Attachments",
  () => [
    { no: 1, name: "pdf", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "xml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "IDnowAbortedPayload_Attachments"},
);

