// @generated by protoc-gen-es v1.2.0
// @generated from file webhook/v1/webhook.proto (package webhook.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { IDnowAbortedPayload, IDnowCanceledPayload, IDnowFraudSuspicionConfirmedPayload, IDnowFraudSuspicionPendingPayload, IDnowReviewPendingPayload, IDnowSuccessDataChangedPayload, IDnowSuccessPayload } from "../../provider/v1/idnow_pb.js";

/**
 * @generated from enum webhook.v1.HookTopic
 */
export declare enum HookTopic {
  /**
   * @generated from enum value: HOOK_TOPIC_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * IDnow
   *
   * @generated from enum value: HOOK_TOPIC_IDNOW_SUCCESS = 1;
   */
  IDNOW_SUCCESS = 1,

  /**
   * @generated from enum value: HOOK_TOPIC_IDNOW_REVIEW_PENDING = 2;
   */
  IDNOW_REVIEW_PENDING = 2,

  /**
   * @generated from enum value: HOOK_TOPIC_IDNOW_FRAUD_SUSPICION_PENDING = 3;
   */
  IDNOW_FRAUD_SUSPICION_PENDING = 3,

  /**
   * @generated from enum value: HOOK_TOPIC_IDNOW_SUCCESS_DATA_CHANGED = 4;
   */
  IDNOW_SUCCESS_DATA_CHANGED = 4,

  /**
   * @generated from enum value: HOOK_TOPIC_IDNOW_FRAUD_SUSPICION_CONFIRMED = 5;
   */
  IDNOW_FRAUD_SUSPICION_CONFIRMED = 5,

  /**
   * @generated from enum value: HOOK_TOPIC_IDNOW_CANCELED = 6;
   */
  IDNOW_CANCELED = 6,

  /**
   * @generated from enum value: HOOK_TOPIC_IDNOW_ABORTED = 7;
   */
  IDNOW_ABORTED = 7,
}

/**
 * @generated from message webhook.v1.IDnowAbortedRequest
 */
export declare class IDnowAbortedRequest extends Message<IDnowAbortedRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowAbortedPayload request = 2;
   */
  request?: IDnowAbortedPayload;

  constructor(data?: PartialMessage<IDnowAbortedRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowAbortedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowAbortedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowAbortedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowAbortedRequest;

  static equals(a: IDnowAbortedRequest | PlainMessage<IDnowAbortedRequest> | undefined, b: IDnowAbortedRequest | PlainMessage<IDnowAbortedRequest> | undefined): boolean;
}

/**
 * @generated from message webhook.v1.IDnowCanceledRequest
 */
export declare class IDnowCanceledRequest extends Message<IDnowCanceledRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowCanceledPayload request = 2;
   */
  request?: IDnowCanceledPayload;

  constructor(data?: PartialMessage<IDnowCanceledRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowCanceledRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowCanceledRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowCanceledRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowCanceledRequest;

  static equals(a: IDnowCanceledRequest | PlainMessage<IDnowCanceledRequest> | undefined, b: IDnowCanceledRequest | PlainMessage<IDnowCanceledRequest> | undefined): boolean;
}

/**
 * @generated from message webhook.v1.IDnowFraudSuspicionConfirmedRequest
 */
export declare class IDnowFraudSuspicionConfirmedRequest extends Message<IDnowFraudSuspicionConfirmedRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowFraudSuspicionConfirmedPayload request = 2;
   */
  request?: IDnowFraudSuspicionConfirmedPayload;

  constructor(data?: PartialMessage<IDnowFraudSuspicionConfirmedRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowFraudSuspicionConfirmedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowFraudSuspicionConfirmedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowFraudSuspicionConfirmedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowFraudSuspicionConfirmedRequest;

  static equals(a: IDnowFraudSuspicionConfirmedRequest | PlainMessage<IDnowFraudSuspicionConfirmedRequest> | undefined, b: IDnowFraudSuspicionConfirmedRequest | PlainMessage<IDnowFraudSuspicionConfirmedRequest> | undefined): boolean;
}

/**
 * @generated from message webhook.v1.IDnowSuccessDataChangedRequest
 */
export declare class IDnowSuccessDataChangedRequest extends Message<IDnowSuccessDataChangedRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowSuccessDataChangedPayload request = 2;
   */
  request?: IDnowSuccessDataChangedPayload;

  constructor(data?: PartialMessage<IDnowSuccessDataChangedRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowSuccessDataChangedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowSuccessDataChangedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowSuccessDataChangedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowSuccessDataChangedRequest;

  static equals(a: IDnowSuccessDataChangedRequest | PlainMessage<IDnowSuccessDataChangedRequest> | undefined, b: IDnowSuccessDataChangedRequest | PlainMessage<IDnowSuccessDataChangedRequest> | undefined): boolean;
}

/**
 * @generated from message webhook.v1.IDnowFraudSuspicionPendingRequest
 */
export declare class IDnowFraudSuspicionPendingRequest extends Message<IDnowFraudSuspicionPendingRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowFraudSuspicionPendingPayload request = 2;
   */
  request?: IDnowFraudSuspicionPendingPayload;

  constructor(data?: PartialMessage<IDnowFraudSuspicionPendingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowFraudSuspicionPendingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowFraudSuspicionPendingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowFraudSuspicionPendingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowFraudSuspicionPendingRequest;

  static equals(a: IDnowFraudSuspicionPendingRequest | PlainMessage<IDnowFraudSuspicionPendingRequest> | undefined, b: IDnowFraudSuspicionPendingRequest | PlainMessage<IDnowFraudSuspicionPendingRequest> | undefined): boolean;
}

/**
 * @generated from message webhook.v1.IDnowReviewPendingRequest
 */
export declare class IDnowReviewPendingRequest extends Message<IDnowReviewPendingRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowReviewPendingPayload request = 2;
   */
  request?: IDnowReviewPendingPayload;

  constructor(data?: PartialMessage<IDnowReviewPendingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowReviewPendingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowReviewPendingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowReviewPendingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowReviewPendingRequest;

  static equals(a: IDnowReviewPendingRequest | PlainMessage<IDnowReviewPendingRequest> | undefined, b: IDnowReviewPendingRequest | PlainMessage<IDnowReviewPendingRequest> | undefined): boolean;
}

/**
 * @generated from message webhook.v1.IDnowSuccessRequest
 */
export declare class IDnowSuccessRequest extends Message<IDnowSuccessRequest> {
  /**
   * @generated from field: string tenant_name = 1;
   */
  tenantName: string;

  /**
   * @generated from field: provider.v1.IDnowSuccessPayload request = 2;
   */
  request?: IDnowSuccessPayload;

  constructor(data?: PartialMessage<IDnowSuccessRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "webhook.v1.IDnowSuccessRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IDnowSuccessRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IDnowSuccessRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IDnowSuccessRequest;

  static equals(a: IDnowSuccessRequest | PlainMessage<IDnowSuccessRequest> | undefined, b: IDnowSuccessRequest | PlainMessage<IDnowSuccessRequest> | undefined): boolean;
}

