// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: event/v1/event.proto

package eventv1

import (
	v1 "github.com/micobo-microservices/core/domain/provider/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic int32

const (
	Topic_TOPIC_UNSPECIFIED Topic = 0
	// IDnow
	Topic_TOPIC_IDNOW_SUCCESS                   Topic = 1
	Topic_TOPIC_IDNOW_REVIEW_PENDING            Topic = 2
	Topic_TOPIC_IDNOW_FRAUD_SUSPICION_PENDING   Topic = 3
	Topic_TOPIC_IDNOW_SUCCESS_DATA_CHANGED      Topic = 4
	Topic_TOPIC_IDNOW_FRAUD_SUSPICION_CONFIRMED Topic = 5
	Topic_TOPIC_IDNOW_CANCELED                  Topic = 6
	Topic_TOPIC_IDNOW_ABORTED                   Topic = 7
)

// Enum value maps for Topic.
var (
	Topic_name = map[int32]string{
		0: "TOPIC_UNSPECIFIED",
		1: "TOPIC_IDNOW_SUCCESS",
		2: "TOPIC_IDNOW_REVIEW_PENDING",
		3: "TOPIC_IDNOW_FRAUD_SUSPICION_PENDING",
		4: "TOPIC_IDNOW_SUCCESS_DATA_CHANGED",
		5: "TOPIC_IDNOW_FRAUD_SUSPICION_CONFIRMED",
		6: "TOPIC_IDNOW_CANCELED",
		7: "TOPIC_IDNOW_ABORTED",
	}
	Topic_value = map[string]int32{
		"TOPIC_UNSPECIFIED":                     0,
		"TOPIC_IDNOW_SUCCESS":                   1,
		"TOPIC_IDNOW_REVIEW_PENDING":            2,
		"TOPIC_IDNOW_FRAUD_SUSPICION_PENDING":   3,
		"TOPIC_IDNOW_SUCCESS_DATA_CHANGED":      4,
		"TOPIC_IDNOW_FRAUD_SUSPICION_CONFIRMED": 5,
		"TOPIC_IDNOW_CANCELED":                  6,
		"TOPIC_IDNOW_ABORTED":                   7,
	}
)

func (x Topic) Enum() *Topic {
	p := new(Topic)
	*p = x
	return p
}

func (x Topic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Topic) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[0].Descriptor()
}

func (Topic) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[0]
}

func (x Topic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Topic.Descriptor instead.
func (Topic) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

type IDnowSuccessPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                  `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowSuccessPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowSuccessPayload) Reset() {
	*x = IDnowSuccessPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowSuccessPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowSuccessPayload) ProtoMessage() {}

func (x *IDnowSuccessPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowSuccessPayload.ProtoReflect.Descriptor instead.
func (*IDnowSuccessPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *IDnowSuccessPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowSuccessPayload) GetPayload() *v1.IDnowSuccessPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IDnowReviewPendingPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                        `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowReviewPendingPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowReviewPendingPayload) Reset() {
	*x = IDnowReviewPendingPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowReviewPendingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowReviewPendingPayload) ProtoMessage() {}

func (x *IDnowReviewPendingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowReviewPendingPayload.ProtoReflect.Descriptor instead.
func (*IDnowReviewPendingPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *IDnowReviewPendingPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowReviewPendingPayload) GetPayload() *v1.IDnowReviewPendingPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IDnowFraudSuspicionPendingPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                                `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowFraudSuspicionPendingPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowFraudSuspicionPendingPayload) Reset() {
	*x = IDnowFraudSuspicionPendingPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowFraudSuspicionPendingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowFraudSuspicionPendingPayload) ProtoMessage() {}

func (x *IDnowFraudSuspicionPendingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowFraudSuspicionPendingPayload.ProtoReflect.Descriptor instead.
func (*IDnowFraudSuspicionPendingPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *IDnowFraudSuspicionPendingPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowFraudSuspicionPendingPayload) GetPayload() *v1.IDnowFraudSuspicionPendingPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IDnowSuccessDataChangedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                             `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowSuccessDataChangedPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowSuccessDataChangedPayload) Reset() {
	*x = IDnowSuccessDataChangedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowSuccessDataChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowSuccessDataChangedPayload) ProtoMessage() {}

func (x *IDnowSuccessDataChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowSuccessDataChangedPayload.ProtoReflect.Descriptor instead.
func (*IDnowSuccessDataChangedPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *IDnowSuccessDataChangedPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowSuccessDataChangedPayload) GetPayload() *v1.IDnowSuccessDataChangedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IDnowFraudSuspicionConfirmedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                                  `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowFraudSuspicionConfirmedPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowFraudSuspicionConfirmedPayload) Reset() {
	*x = IDnowFraudSuspicionConfirmedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowFraudSuspicionConfirmedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowFraudSuspicionConfirmedPayload) ProtoMessage() {}

func (x *IDnowFraudSuspicionConfirmedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowFraudSuspicionConfirmedPayload.ProtoReflect.Descriptor instead.
func (*IDnowFraudSuspicionConfirmedPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *IDnowFraudSuspicionConfirmedPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowFraudSuspicionConfirmedPayload) GetPayload() *v1.IDnowFraudSuspicionConfirmedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IDnowCanceledPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                   `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowCanceledPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowCanceledPayload) Reset() {
	*x = IDnowCanceledPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowCanceledPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowCanceledPayload) ProtoMessage() {}

func (x *IDnowCanceledPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowCanceledPayload.ProtoReflect.Descriptor instead.
func (*IDnowCanceledPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *IDnowCanceledPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowCanceledPayload) GetPayload() *v1.IDnowCanceledPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IDnowAbortedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantName string                  `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Payload    *v1.IDnowAbortedPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IDnowAbortedPayload) Reset() {
	*x = IDnowAbortedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_v1_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDnowAbortedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDnowAbortedPayload) ProtoMessage() {}

func (x *IDnowAbortedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDnowAbortedPayload.ProtoReflect.Descriptor instead.
func (*IDnowAbortedPayload) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *IDnowAbortedPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *IDnowAbortedPayload) GetPayload() *v1.IDnowAbortedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_event_v1_event_proto protoreflect.FileDescriptor

var file_event_v1_event_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x17, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x64,
	0x6e, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x13, 0x49, 0x44, 0x6e,
	0x6f, 0x77, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x3a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x7e, 0x0a,
	0x19, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x44, 0x6e, 0x6f, 0x77,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8e, 0x01,
	0x0a, 0x21, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x46, 0x72, 0x61, 0x75, 0x64, 0x53, 0x75, 0x73, 0x70,
	0x69, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x46, 0x72, 0x61, 0x75, 0x64, 0x53, 0x75,
	0x73, 0x70, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x88,
	0x01, 0x0a, 0x1e, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x45, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x23, 0x49, 0x44,
	0x6e, 0x6f, 0x77, 0x46, 0x72, 0x61, 0x75, 0x64, 0x53, 0x75, 0x73, 0x70, 0x69, 0x63, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x46, 0x72, 0x61, 0x75, 0x64, 0x53, 0x75, 0x73, 0x70,
	0x69, 0x63, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x74,
	0x0a, 0x14, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x72, 0x0a, 0x13, 0x49, 0x44, 0x6e, 0x6f, 0x77, 0x41, 0x62, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x44, 0x6e, 0x6f,
	0x77, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x84, 0x02, 0x0a, 0x05, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x4f, 0x50,
	0x49, 0x43, 0x5f, 0x49, 0x44, 0x4e, 0x4f, 0x57, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x4e, 0x4f,
	0x57, 0x5f, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x27, 0x0a, 0x23, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x4e, 0x4f,
	0x57, 0x5f, 0x46, 0x52, 0x41, 0x55, 0x44, 0x5f, 0x53, 0x55, 0x53, 0x50, 0x49, 0x43, 0x49, 0x4f,
	0x4e, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x24, 0x0a, 0x20, 0x54,
	0x4f, 0x50, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x4e, 0x4f, 0x57, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x44, 0x10,
	0x04, 0x12, 0x29, 0x0a, 0x25, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x4e, 0x4f, 0x57,
	0x5f, 0x46, 0x52, 0x41, 0x55, 0x44, 0x5f, 0x53, 0x55, 0x53, 0x50, 0x49, 0x43, 0x49, 0x4f, 0x4e,
	0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x45, 0x44, 0x10, 0x05, 0x12, 0x18, 0x0a, 0x14,
	0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x4e, 0x4f, 0x57, 0x5f, 0x43, 0x41, 0x4e, 0x43,
	0x45, 0x4c, 0x45, 0x44, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f,
	0x49, 0x44, 0x4e, 0x4f, 0x57, 0x5f, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x07, 0x42,
	0x99, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x42, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x6f, 0x62,
	0x6f, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x45,
	0x58, 0x58, 0xaa, 0x02, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_event_v1_event_proto_rawDescOnce sync.Once
	file_event_v1_event_proto_rawDescData = file_event_v1_event_proto_rawDesc
)

func file_event_v1_event_proto_rawDescGZIP() []byte {
	file_event_v1_event_proto_rawDescOnce.Do(func() {
		file_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_v1_event_proto_rawDescData)
	})
	return file_event_v1_event_proto_rawDescData
}

var file_event_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_event_v1_event_proto_goTypes = []interface{}{
	(Topic)(0),                                     // 0: event.v1.Topic
	(*IDnowSuccessPayload)(nil),                    // 1: event.v1.IDnowSuccessPayload
	(*IDnowReviewPendingPayload)(nil),              // 2: event.v1.IDnowReviewPendingPayload
	(*IDnowFraudSuspicionPendingPayload)(nil),      // 3: event.v1.IDnowFraudSuspicionPendingPayload
	(*IDnowSuccessDataChangedPayload)(nil),         // 4: event.v1.IDnowSuccessDataChangedPayload
	(*IDnowFraudSuspicionConfirmedPayload)(nil),    // 5: event.v1.IDnowFraudSuspicionConfirmedPayload
	(*IDnowCanceledPayload)(nil),                   // 6: event.v1.IDnowCanceledPayload
	(*IDnowAbortedPayload)(nil),                    // 7: event.v1.IDnowAbortedPayload
	(*v1.IDnowSuccessPayload)(nil),                 // 8: provider.v1.IDnowSuccessPayload
	(*v1.IDnowReviewPendingPayload)(nil),           // 9: provider.v1.IDnowReviewPendingPayload
	(*v1.IDnowFraudSuspicionPendingPayload)(nil),   // 10: provider.v1.IDnowFraudSuspicionPendingPayload
	(*v1.IDnowSuccessDataChangedPayload)(nil),      // 11: provider.v1.IDnowSuccessDataChangedPayload
	(*v1.IDnowFraudSuspicionConfirmedPayload)(nil), // 12: provider.v1.IDnowFraudSuspicionConfirmedPayload
	(*v1.IDnowCanceledPayload)(nil),                // 13: provider.v1.IDnowCanceledPayload
	(*v1.IDnowAbortedPayload)(nil),                 // 14: provider.v1.IDnowAbortedPayload
}
var file_event_v1_event_proto_depIdxs = []int32{
	8,  // 0: event.v1.IDnowSuccessPayload.payload:type_name -> provider.v1.IDnowSuccessPayload
	9,  // 1: event.v1.IDnowReviewPendingPayload.payload:type_name -> provider.v1.IDnowReviewPendingPayload
	10, // 2: event.v1.IDnowFraudSuspicionPendingPayload.payload:type_name -> provider.v1.IDnowFraudSuspicionPendingPayload
	11, // 3: event.v1.IDnowSuccessDataChangedPayload.payload:type_name -> provider.v1.IDnowSuccessDataChangedPayload
	12, // 4: event.v1.IDnowFraudSuspicionConfirmedPayload.payload:type_name -> provider.v1.IDnowFraudSuspicionConfirmedPayload
	13, // 5: event.v1.IDnowCanceledPayload.payload:type_name -> provider.v1.IDnowCanceledPayload
	14, // 6: event.v1.IDnowAbortedPayload.payload:type_name -> provider.v1.IDnowAbortedPayload
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_event_v1_event_proto_init() }
func file_event_v1_event_proto_init() {
	if File_event_v1_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_v1_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowSuccessPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_v1_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowReviewPendingPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_v1_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowFraudSuspicionPendingPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_v1_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowSuccessDataChangedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_v1_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowFraudSuspicionConfirmedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_v1_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowCanceledPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_v1_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDnowAbortedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_v1_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_v1_event_proto_goTypes,
		DependencyIndexes: file_event_v1_event_proto_depIdxs,
		EnumInfos:         file_event_v1_event_proto_enumTypes,
		MessageInfos:      file_event_v1_event_proto_msgTypes,
	}.Build()
	File_event_v1_event_proto = out.File
	file_event_v1_event_proto_rawDesc = nil
	file_event_v1_event_proto_goTypes = nil
	file_event_v1_event_proto_depIdxs = nil
}
