// @generated by protoc-gen-es v1.2.0
// @generated from file common/v1/response.proto (package common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message common.v1.ErrorResponse
 */
export const ErrorResponse = proto3.makeMessageType(
  "common.v1.ErrorResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message common.v1.BoolResponse
 */
export const BoolResponse = proto3.makeMessageType(
  "common.v1.BoolResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

