// @generated by protoc-gen-es v1.2.0
// @generated from file common/v1/response.proto (package common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message common.v1.ErrorResponse
 */
export declare class ErrorResponse extends Message<ErrorResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  constructor(data?: PartialMessage<ErrorResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "common.v1.ErrorResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ErrorResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ErrorResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ErrorResponse;

  static equals(a: ErrorResponse | PlainMessage<ErrorResponse> | undefined, b: ErrorResponse | PlainMessage<ErrorResponse> | undefined): boolean;
}

/**
 * @generated from message common.v1.BoolResponse
 */
export declare class BoolResponse extends Message<BoolResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  constructor(data?: PartialMessage<BoolResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "common.v1.BoolResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BoolResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BoolResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BoolResponse;

  static equals(a: BoolResponse | PlainMessage<BoolResponse> | undefined, b: BoolResponse | PlainMessage<BoolResponse> | undefined): boolean;
}

